name: Deploy to Digital Ocean droplet
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/nodejs/bootcamp
          git pull
          npm run build
          pm2 start ./api/server.js
